extends SceneTree
## One-shot: import the Jersey 25 font crisply and save res://default_theme.tres
## with it as the default font, then point the project at it. Generated by the
## engine so the Theme/FontFile resources are guaranteed valid.
##
## Run: godot --headless --path . --script res://tools/gen_theme.gd


func _init() -> void:
	var font := FontFile.new()
	font.load_dynamic_font("res://assets/fonts/Jersey25-Regular.ttf")
	# Jersey 25 is a pixel-style face; kill antialiasing/hinting so it stays
	# crisp and blocky instead of blurring into the CRT/pixelation pass.
	font.antialiasing = TextServer.FONT_ANTIALIASING_NONE
	font.hinting = TextServer.HINTING_NONE
	font.subpixel_positioning = TextServer.SUBPIXEL_POSITIONING_DISABLED
	var ferr: int = ResourceSaver.save(font, "res://assets/fonts/jersey25.tres")

	var theme := Theme.new()
	theme.default_font = font
	theme.default_font_size = 24
	var terr: int = ResourceSaver.save(theme, "res://default_theme.tres")

	print("[verify] font err=%d theme err=%d" % [ferr, terr])
	quit(1 if (ferr != OK or terr != OK) else 0)
