extends SceneTree
## One-shot generator for res://default_bus_layout.tres — the Master/Music/SFX
## bus tree the options menu drives. Generated by the engine rather than
## hand-authored so the resource format is guaranteed correct.
##
## Run: godot --headless --path . --script res://tools/gen_bus_layout.gd


func _init() -> void:
	# Start from a clean tree: Master is index 0 and cannot be removed.
	while AudioServer.bus_count > 1:
		AudioServer.remove_bus(AudioServer.bus_count - 1)

	AudioServer.add_bus(1)
	AudioServer.set_bus_name(1, "Music")
	AudioServer.set_bus_send(1, "Master")

	AudioServer.add_bus(2)
	AudioServer.set_bus_name(2, "SFX")
	AudioServer.set_bus_send(2, "Master")

	var layout: AudioBusLayout = AudioServer.generate_bus_layout()
	var err: int = ResourceSaver.save(layout, "res://default_bus_layout.tres")
	var names: Array[String] = []
	for i in AudioServer.bus_count:
		names.append(AudioServer.get_bus_name(i))
	print("[verify] bus layout saved err=%d buses=%s" % [err, names])
	quit(1 if err != OK else 0)
